In [1]:
import pandas as pd
import numpy as np
import csv 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('./data_set/titanic_kor.csv', encoding='cp949')
df

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
df.head(3)

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [7]:
df.columns

Index(['생존', '등급', '성별', '나이', '형제자매', '부모자녀', '요금', '탑승지코드', '객실등급', '성인여부',
       '성인남성', '선실코드', '탑승지명', '생존여부', '개인탑승자'],
      dtype='object')

In [8]:
df.describe

<bound method NDFrame.describe of      생존  등급      성별    나이  형제자매  부모자녀       요금 탑승지코드    객실등급   성인여부   성인남성  \
0     0   3    male  22.0     1     0   7.2500     S   Third    man   True
1     1   1  female  38.0     1     0  71.2833     C   First  woman  False
2     1   3  female  26.0     0     0   7.9250     S   Third  woman  False
3     1   1  female  35.0     1     0  53.1000     S   First  woman  False
4     0   3    male  35.0     0     0   8.0500     S   Third    man   True
..   ..  ..     ...   ...   ...   ...      ...   ...     ...    ...    ...
886   0   2    male  27.0     0     0  13.0000     S  Second    man   True
887   1   1  female  19.0     0     0  30.0000     S   First  woman  False
888   0   3  female   NaN     1     2  23.4500     S   Third  woman  False
889   1   1    male  26.0     0     0  30.0000     C   First    man   True
890   0   3    male  32.0     0     0   7.7500     Q   Third    man   True

    선실코드         탑승지명 생존여부  개인탑승자
0    NaN  Southampton   no  False
1      C    Cherbourg  yes  False
2    NaN  Southampton  yes   True
3      C  Southampton  yes  False
4    NaN  Southampton   no   True
..   ...          ...  ...    ...
886  NaN  Southampton   no   True
887    B  Southampton  yes   True
888  NaN  Southampton   no  False
889    C    Cherbourg  yes   True
890  NaN   Queenstown   no   True

[891 rows x 15 columns]>

In [9]:
df.describe(include="all")

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.dtypes

생존         int64
등급         int64
성별        object
나이       float64
형제자매       int64
부모자녀       int64
요금       float64
탑승지코드     object
객실등급      object
성인여부      object
성인남성        bool
선실코드      object
탑승지명      object
생존여부      object
개인탑승자       bool
dtype: object

In [10]:
df[['객실등급','요금']]

       객실등급       요금
0     Third   7.2500
1     First  71.2833
2     Third   7.9250
3     First  53.1000
4     Third   8.0500
..      ...      ...
886  Second  13.0000
887   First  30.0000
888   Third  23.4500
889   First  30.0000
890   Third   7.7500

[891 rows x 2 columns]

In [12]:
df.loc[10:15]

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True

In [14]:
df.loc[21:23,['객실등급','요금']]

      객실등급       요금
21  Second  13.0000
22   Third   8.0292
23   First  35.5000