## 데이터 분석 마무리 과제 - 타이타닉 데이터 분석

연습문제 데이터 파일 : titanic_kor.csv  

> 타이타닉호의 침몰은 역사상 가장 참혹한 선박 침몰 사고 중 하나이다.  
> 1912년 4월 15일, 첫 항해 중 절대 "침몰할 수 없는" 것으로 여겨졌던 RMS 타이타닉호가 빙산과 충돌한 후 침몰하게 되었다.  
> 불행히도 탑승객 모두를 태울 구명보트가 충분하지 않아 승객과 승무원 2,224명 중 1,502명이 사망하게 되었다.  
> 살아남는 데는 어느 정도 운이 작용하겠지만, 어떤 집단은 다른 집단보다 생존 가능성이 더 큰 듯 보였다.  

**아래의 승객 데이터(이름, 나이, 성별, 사회경제적 계층 등)를 사용하여  
"어떤 사람들이 생존 가능성이 더 높을까?"라는 질문에 답할 수 있는 데이터 분석을 수행해 보자.**
  
생존 : 생존여부 (0=사망, 1=생존)  
등급 : 티켓 클래스(1=1등석, 2=2등석, 3=3등석)  
성별 : 성별  
나이 : 나이  
형제자매 : 함께 탑승한 형제/자매  
부모자녀 : 함께 탑승한 부모/자녀  
요금 : 탑승 요금  
탑승지코드 : 탑승지 코드  
객실등급 : 객실 등급(1=1등석, 2=2등석, 3=3등석)  
성인여부 : 남여 성인 여부  
성인남성 : 성인 남성 여부  
선실코드 : 선실 코드  
탐승지명 : 선착장  
생존여부 : 생존 여부(no=사망, yes=생존)  
개인탑승자 : 개인 탑승자 여부

#### 과제 풀기

In [1]:
#문제1. pands, numpy, csv, matplotlib 라이브러리를 불러오시오.
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt

In [2]:
#문제2. 타이타닉(titani) 데이터셋을 불러오시오.
#df = pd.read_csv("titanic_kor.csv") #UTF-8 인코딩에러발생
df = pd.read_csv("./data_set/titanic_kor.csv",encoding='CP949')
df

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
#문제3. 데이터셋에서 처음 3개 행을 출력하시오.
df.head(3)

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [4]:
#문제4. 데이터셋의 컬럼 명을 출력하시오.
df.columns

Index(['생존', '등급', '성별', '나이', '형제자매', '부모자녀', '요금', '탑승지코드', '객실등급', '성인여부',
       '성인남성', '선실코드', '탑승지명', '생존여부', '개인탑승자'],
      dtype='object')

In [5]:
#문제5. 데이터셋에 대한 통계자료를 출력하시오.
df.describe()

               생존          등급          나이        형제자매        부모자녀          요금
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
# 혹시 숫자가 아닌 컬룸들까지 포함하여 통계자료를 만들려고 한다면.
df.describe(include="all")

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#문제6. 데이터셋의 각 컬럼에 대한 데이터 형식(int, object, float...)을 출력하시오.
df.dtypes

생존         int64
등급         int64
성별        object
나이       float64
형제자매       int64
부모자녀       int64
요금       float64
탑승지코드     object
객실등급      object
성인여부      object
성인남성        bool
선실코드      object
탑승지명      object
생존여부      object
개인탑승자       bool
dtype: object

In [8]:
#문제7. '객실등급' 컬럼과 '요금' 컬럼에 대한 데이터만 출력하시오.
df[['객실등급', '요금']]

       객실등급       요금
0     Third   7.2500
1     First  71.2833
2     Third   7.9250
3     First  53.1000
4     Third   8.0500
..      ...      ...
886  Second  13.0000
887   First  30.0000
888   Third  23.4500
889   First  30.0000
890   Third   7.7500

[891 rows x 2 columns]

In [9]:
#문제8. 인덱스 10 ~ 15번 행에 대한 데이터만 출력하시오.
df.loc[10:15]

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True

In [10]:
#문제9. '객실등급' 컬럼과 '요금' 컬럼에 대한 인덱스 21 ~ 23번 행의 데이터만 출력하시오.
df.loc[21:23, ['객실등급', '요금']]

      객실등급       요금
21  Second  13.0000
22   Third   8.0292
23   First  35.5000

In [11]:
#문제10. 객실 요금이 300 불 이상인 데이터에 대한 '성별', '나이', '객실등급', '생존여부' 컬럼을 출력하시오.
df.loc[df['요금'] >= 300, ['성별', '나이', '객실등급', '생존여부']]

         성별    나이   객실등급 생존여부
258  female  35.0  First  yes
679    male  36.0  First  yes
737    male  35.0  First  yes

In [12]:
#문제11. '객실등급'의 데이터 값을 모두 소문자로 바꾸고 출력하시오. (First -> first, Second -> second, Third -> third)
df['객실등급'] = df['객실등급'].str.lower()
df['객실등급']

0       third
1       first
2       third
3       first
4       third
        ...
886    second
887     first
888     third
889     first
890     third
Name: 객실등급, Length: 891, dtype: object

In [13]:
#문제12. '성인여부' 컬럼의 데이터 값 중 man, woman 을 adult 로 바꾸시오.
df['성인여부'] = df['성인여부'].replace({'man': 'adult', 'woman': 'adult'})
df['성인여부']

0      adult
1      adult
2      adult
3      adult
4      adult
       ...
886    adult
887    adult
888    adult
889    adult
890    adult
Name: 성인여부, Length: 891, dtype: object

In [14]:
#문제13. 데이터 셋의 각 컬럼에 대한 공백(결측치)의 갯수를 출력하시오.
df.isnull().sum()

생존         0
등급         0
성별         0
나이       177
형제자매       0
부모자녀       0
요금         0
탑승지코드      2
객실등급       0
성인여부       0
성인남성       0
선실코드     688
탑승지명       2
생존여부       0
개인탑승자      0
dtype: int64

In [15]:
#문제14. 데이터셋에는 총 몇 건의 데이터가 저장되어 있는지 출력하시오(전체 탑승자는 몇 명인가).
print("전체 탑승자 수:", len(df))
print("전체 탑승자 수:", df.shape) # tuple (891, 15)
print("전체 탑승자 수:", df.shape[0])

전체 탑승자 수: 891
전체 탑승자 수: (891, 15)
전체 탑승자 수: 891

In [16]:
#문제15. '생존여부' 컬럼의 데이터와 비교하여 '생존' 컬럼의 데이터 값이 동일한지를 확인하시오. 
#('생존' 컬럼의 데이터가 1 일때, '생존여부' 컬럼의 데이터가 no 이라면 서로 다른 데이터이다. 해당 데이터가 있는지를 찾으면 된다.)
mismatch = df[(df['생존'] == 1) & (df['생존여부'] == 'no')]
mismatch
# 행이 하나도 없음. 즉, 생존,생존여부 데이터의 불일치 문제는 없음.

Empty DataFrame
Columns: [생존, 등급, 성별, 나이, 형제자매, 부모자녀, 요금, 탑승지코드, 객실등급, 성인여부, 성인남성, 선실코드, 탑승지명, 생존여부, 개인탑승자]
Index: []

In [17]:
#문제16. '생존' 컬럼과 동일한 값이 저장되어 있는 '생존여부' 컬럼을 삭제하시오. 
#그리고 '등급' 컬럼과 동일한 값이 저장되어 있는 '객실등급' 컬럼을 삭제하시오.
df = df.drop(columns=['생존여부', '객실등급'])
df.head()

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,성인여부,성인남성,선실코드,탑승지명,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,adult,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,adult,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,adult,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,adult,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,adult,True,NaN,Southampton,True

In [18]:
#문제17. '탑승지코드' 컬럼과 '탑승지명' 컬럼 모두에서 데이터 값이 누락되어 있는 행(인덱스)을 찾으시오.
df[df['탑승지코드'].isnull() & df['탑승지명'].isnull()].index

Index([61, 829], dtype='int64')

In [19]:
#문제18. '탑승지코드' 컬럼과 '탑승지명' 컬럼에서 결측치(데이터가 누락되어 있는)가 존재하는 행을 삭제하시오. (인덱스 61, 829 번 행에 결측치가 존재한다.)
df = df.dropna(subset=['탑승지코드', '탑승지명'])
df.shape  
# 원래 행개수 : 891 ==> 889 로 2개 제거된 것 확인.

(889, 13)

In [20]:
#문제19. 인덱스 59 ~ 63번 행에 대한 데이터만 출력하시오.
df.loc[59:63]

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,성인여부,성인남성,선실코드,탑승지명,개인탑승자
59,0,3,male,11.0,5,2,46.9000,S,child,False,NaN,Southampton,False
60,0,3,male,22.0,0,0,7.2292,C,adult,True,NaN,Cherbourg,True
62,0,1,male,45.0,1,0,83.4750,S,adult,True,C,Southampton,False
63,0,3,male,4.0,3,2,27.9000,S,child,False,NaN,Southampton,False

In [21]:
#문제20. '성인여부' 컬럼에서 child 데이터에 대응하는 '나이' 컬럼의 데이터가 누락되어 있는지 확인하시오. 
#('성인여부' 컬럼의 데이터가 child 일때, '나이' 컬럼의 데이터가 isnull 인 데이터를 찾으면 된다.)
df[(df['성인여부'] == 'child') & (df['나이'].isnull())]
# 아이들 중 나이에 결측지는 존재하지 않음.

Empty DataFrame
Columns: [생존, 등급, 성별, 나이, 형제자매, 부모자녀, 요금, 탑승지코드, 성인여부, 성인남성, 선실코드, 탑승지명, 개인탑승자]
Index: []

In [22]:
#문제21. '나이' 컬럼의 데이터 값에 대한 평균을 출력하시오.
print("나이 평균:", df['나이'].mean())

나이 평균: 29.64209269662921

In [23]:
#문제22. '나이' 컬럼의 결측치(빈 셀)를 '나이'에 대한 평균 값으로 채우시오. 
df['나이'] = df['나이'].fillna(df['나이'].mean()) # 나이 결측값이 177개 였음.
print(df['나이'].isnull().sum())

0

In [24]:
#문제23. '선실코드' 컬럼의 데이터 값에는 어떤 종류의 값이 있는지 출력하시오(7 개).
df['선실코드'].unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F'], dtype=object)

In [25]:
#문제24. '요금' 컬럼에서 가장 높은 요금이 얼마인지 출력하시오.
print("최고 요금:", df['요금'].max())

최고 요금: 512.3292

In [26]:
#문제25. 생존자에 대한 데이터만 출력하시오. ('생존' 컬럼의 데이터 값이 1 인 데이터를 추출하여 'survivor' 변수에 저장한 다음 출력하시오.)
survivor = df[df['생존'] == 1] # survivor:생존자
survivor 
# 데이터프레임 출력의 마지막에  '340 rows x 13 columns' 가 출력된 것을 확인할 수 있음. [340명의 생존자 확인]

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,성인여부,성인남성,선실코드,탑승지명,개인탑승자
1,1,1,female,38.0,1,0,71.2833,C,adult,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,adult,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,adult,False,C,Southampton,False
8,1,3,female,27.0,0,2,11.1333,S,adult,False,NaN,Southampton,False
9,1,2,female,14.0,1,0,30.0708,C,child,False,NaN,Cherbourg,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,child,False,NaN,Cherbourg,True
879,1,1,female,56.0,0,1,83.1583,C,adult,False,C,Cherbourg,False
880,1,2,female,25.0,0,1,26.0000,S,adult,False,NaN,Southampton,False
887,1,1,female,19.0,0,0,30.0000,S,adult,False,B,Southampton,True
889,1,1,male,26.0,0,0,30.0000,C,adult,True,C,Cherbourg,True

In [27]:
#문제26. '객실등급' 별 승객수를 출력하시오.
# print(df['객실등급'].value_counts())  #에러 - 이전 과제에서 '객실등급'룸을 삭제했음. 
df['등급'].value_counts() # 대신 '등급' 칸을 통해 객실등급별 값들의 개수를 확인할 수 있은.

등급
3    491
1    214
2    184
Name: count, dtype: int64

In [28]:
#문제27. '객실등급' 별 최고 요금을 출력하시오.
df.groupby('등급')['요금'].max()

등급
1    512.3292
2     73.5000
3     69.5500
Name: 요금, dtype: float64

In [29]:
#문제28. '객실등급'별 승객의 평균 나이를 출력하시오.
df.groupby('등급')['나이'].mean()

등급
1    36.919078
2    29.863549
3    26.387464
Name: 나이, dtype: float64

In [30]:
#문제29. '생존'과 '나이' 컬럼을 기준으로 내림차순 정렬한 다음, 20개의 데이터만 표시하시오.
df.sort_values(by=['생존', '나이'], ascending=False).head(20)

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,성인여부,성인남성,선실코드,탑승지명,개인탑승자
630,1,1,male,80.0,0,0,30.0000,S,adult,True,A,Southampton,True
275,1,1,female,63.0,1,0,77.9583,S,adult,False,D,Southampton,False
483,1,3,female,63.0,0,0,9.5875,S,adult,False,NaN,Southampton,True
570,1,2,male,62.0,0,0,10.5000,S,adult,True,NaN,Southampton,True
366,1,1,female,60.0,1,0,75.2500,C,adult,False,D,Cherbourg,False
587,1,1,male,60.0,1,1,79.2000,C,adult,True,B,Cherbourg,False
11,1,1,female,58.0,0,0,26.5500,S,adult,False,C,Southampton,True
195,1,1,female,58.0,0,0,146.5208,C,adult,False,B,Cherbourg,True
268,1,1,female,58.0,0,1,153.4625,S,adult,False,C,Southampton,False
647,1,1,male,56.0,0,0,35.5000,C,adult,True,A,Cherbourg,True
879,1,1,female,56.0,0,1,83.1583,C,adult,False,C,Cherbourg,False
15,1,2,female,55.0,0,0,16.0000,S,adult,False,NaN,Southampton,True
496,1,1,female,54.0,1,0,78.2667,C,adult,False,D,Cherbourg,False
513,1,1,female,54.0,1,0,59.4000,C,adult,False,NaN,Cherbourg,False
774,1,2,female,54.0,1,3,23.0000,S,adult,False,NaN,Southampton,False
571,1,1,female,53.0,2,0,51.4792,S,adult,False,C,Southampton,False
449,1,1,male,52.0,0,0,30.5000,S,adult,True,C,Southampton,True
591,1,1,female,52.0,1,0,78.2667,C,adult,False,D,Cherbourg,False
820,1,1,female,52.0,1,1,93.5000,S,adult,False,B,Southampton,False
765,1,1,female,51.0,1,0,77.9583,S,adult,False,D,Southampton,False

In [31]:
#문제30. 여성 생존율과 남성 생존율을 아래와 같이 표시하시오.
female_survival_rate = df[df['성별'] == 'female']['생존'].mean()
male_survival_rate = df[df['성별'] == 'male']['생존'].mean()

print("여성 생존율 =", round(female_survival_rate, 2))
print("남성 생존율 =", round(male_survival_rate, 2))

여성 생존율 = 0.74
남성 생존율 = 0.19

In [32]:
# [슬라이드로 소개 참고]

# 목표 : 승객 데이터(이름, 나이, 성별, 사회경제적 계층 등)를 사용하여 "어떤 사람들이 생존 가능성이 더 높을까?"라는 질문에 답할 수 있는 데이터 분석을 수행


# 1단계. 문제 정의
#  - 목표: 타이타닉 탑승객 중 어떤 특성을 가진 사람들이 생존할 확률이 높았는지 파악
#  - 주요 변수 후보: 성별, 나이, 객실등급, 탑승지, 요금, 동승자 수 등

# 2단계. 데이터 이해 및 전처리
#  - 결측치 처리: 나이, 탑승지코드, 선실코드 등에 결측치가 있는지 확인하고 평균/중앙값 대체 또는 삭제
#  - 데이터 변환: 범주형 → 숫자형 변환 (예: 성별 male=0, female=1).  필요 없는 중복된 컬럼 제거 (이전 과제에서 한 것처럼)
#  - 파생 변수 생성:
#    가족수 = 형제자매수 + 부모자녀수 + 1
#    연령대 = (어린이/청년/중년/노인 등)

# 3단계. 탐색적 데이터 분석 (EDA)
#  - 기초 통계: 생존/사망자 수 비율 확인
#  - 시각화:
#    성별 vs 생존율 (막대그래프)
#    객실등급 vs 생존율 (막대그래프)
#    나이 분포와 생존 여부 (히스토그램, KDE Plot)
#    요금 vs 생존 여부 (박스플롯)
#  - 교차분석:
#    성별 + 객실등급 → 생존율
#    가족 유무 → 생존율

# 4단계. 통계적 분석
#  - 성별/객실등급과 생존 여부의 관계 유의성 확인
#  - 생존자 vs 사망자의 나이 평균 비교

# 5단계. 해석 및 결론
#  - “여성, 1등석 승객, 어린이, 요금이 높은 승객, 가족이 함께 있는 경우”  → 생존 확률 70%
#  - “남성, 3등석 승객, 나이가 많은 승객” → 생존 확률 20%


# [ 확장. AI 예측 모델링 ]
#  - 로지스틱 회귀: 생존 여부에 영향을 주는 요인을 계수로 확인
#  - 의사결정나무/랜덤포레스트: 변수 중요도 확인
#  - 교차검증: 모델 성능 평가